//alerts
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//Authentication
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL' //invalid OTP
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const OTP_REQUEST_SENT = 'OTP_REQUEST_SENT'
export const OTP_RECEIVED = 'OTP_RECEIVED'
export const OTP_VALIDATE_REQUEST = 'OTP_VALIDATE_REQUEST'
export const LOGOUT = 'LOGOUT'

//Sidebar
export const GET_BRAND = 'GET_BRAND'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_SIDEBAR_ERROR = 'GET_SIDEBAR_ERROR'

//Profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_UPDATE = 'PROFILE_UPDATE'
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_ERROR = 'PROFILE_ERROR'


//Load Products List
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

//Cart
export const CART_REQUEST = 'CART_REQUEST'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const CART_ERROR = 'CART_ERROR'
export const GET_CART_DATA = 'GET_CART_DATA'


//Wishlist
export const WISHLIST_REQUEST = 'WISHLIST_REQUEST'
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST'
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST'
export const WISHLIST_ERROR = 'WISHLIST_ERROR'
export const GET_WISHLIST_DATA = 'GET_WISHLIST_DATA'


//banner
export const BANNER_REQUEST = 'BANNER_REQUEST'
export const BANNER_GET = 'BANNER_GET'
export const BANNER_ERROR = 'BANNER_ERROR'


//location
export const GET_COUNTRY_BILLING = 'GET_COUNTRY_BILLING'

export const GET_STATE_BILLING = 'GET_STATE_BILLING'
export const GET_CITY_BILLING = 'GET_CITY_BILLING'
export const GET_PINCODE_BILLING = 'GET_PINCODE_BILLING'
export const GET_AREA_BILLING = 'GET_AREA_BILLING'
export const GET_SOCIETY_BILLING= 'GET_SOCIETY_BILLING'
export const GET_TOWER_BILLING = 'GET_TOWER_BILLING'

export const GET_STATE_SHIPPING = 'GET_STATE_SHIPPING'
export const GET_CITY_SHIPPING = 'GET_CITY_SHIPPING'
export const GET_PINCODE_SHIPPING = 'GET_PINCODE_SHIPPING'
export const GET_AREA_SHIPPING = 'GET_AREA_SHIPPING'
export const GET_SOCIETY_SHIPPING = 'GET_SOCIETY_SHIPPING'
export const GET_TOWER_SHIPPING = 'GET_TOWER_SHIPPING'

export const LOCATION_REQUEST = 'LOCATION_REQUEST'
export const LOCATION_ERROR = 'LOCATION_ERROR'


//load filtered products list
export const GET_FILTERED_PRODUCTS = 'GET_FILTERED_PRODUCTS'
export const GET_FILTERED_PRODUCTS_ERROR = 'GET_FILTERED_PRODUCTS_ERROR'